# Generated by Django 5.2.5 on 2026-06-13 00:23

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_details',
            field=apps.core.fields.EncryptedTextField(blank=True, max_length=500, null=True),
        ),
    ]
