# Generated by Django 5.2.5 on 2026-06-13 02:07

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_details',
            field=apps.core.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
